### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by stoe** [githubschool/312-gh4m#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by oliveralbrecht73** [comment]
Hi,

Oliver Albrecht, Product Owner BMW Symphony

**Comment by mttkrss** [comment]
Auch da.

matthias

**Comment by PatBMW** [comment]
Moin,

Patrick Pastoor, Scrum Master & FO AUTOSAR for Symphony.

**Comment by BerndHorn** [comment]
Bernd Horn, FG-401 BRM
Kontakt für E/E bei FG-4.
Und Scrum Master FG-40.

**Comment by stoe** [comment]
Hallo.

Stefan Stölzle, GitHub Professional Services Engineer

![](https://github.com/stoe.png)

**Comment by MihaiSicoe** [comment]
Hallo,
Mihai Sicoe, JC42, AIDA Symphony Developer

**Comment by aHwE** [comment]
# Harald Wenke
## PL Codecraft

**Comment by stoe** [comment]
@stoe, @aHwE

**Comment by GeraldManger** [comment]
Gerald Manger, EE-341
