### ISSUE TITLE
Create new ... - PatBMW

### ISSUE THREAD

**Issue by PatBMW** [githubschool/312-gh4m#10]
Be sure to fill out the template below when submitting a new Issue!

- **Description:** _Enter description here_

**Comment by oliveralbrecht73** [comment]
:man_technologist:  :1st_place_medal:

**Comment by oliveralbrecht73** [comment]
:bug: :bee: :beetle:

**Comment by oliveralbrecht73** [comment]
:recycle: :bikini: :biohazard:

**Comment by PatBMW** [comment]
🛒 🐒  <= shopping monkey

**Comment by PatBMW** [comment]
🎷 🐛  <= saxoohonspielende raupe

**Comment by oliveralbrecht73** [comment]
:musical_keyboard: :drum:

**Comment by oliveralbrecht73** [comment]
:musical_score:  Symphony

**Comment by PatBMW** [comment]
🎮 🏹

**Comment by PatBMW** [comment]
✈️

**Comment by oliveralbrecht73** [comment]
:space_invader:

**Comment by PatBMW** [comment]
💰

**Comment by oliveralbrecht73** [comment]
:hamburger: :beer:

**Comment by PatBMW** [comment]
🐳
